import { Router, Response } from 'express';

const router = Router();        
router.get('/duplecates', (_, res: Response) => {

    let fullArray = [ 'Actuarial Science',
    'Complex Numbers',
    'Imaginary Numbers',
    'Quaternions',
    'Octonions',
    'Differential Equations',
    'Bayesian Statistics',
    'Regression Analysis',
    'Descriptive Statistics',
    'Graph Theory',
    'Vector Spaces',
    'Multivariable Calculus',
    'Integral Calculus',
    'Differential Calculus',
    'Pre-Algebra Basic',
    'Modal Logic',
    'Prealgebra',
    'Finite Math',
    'Differential Equations',
    'Discrete Math',
    'Elementary Math',
    'Quadratic Formula',
    'Arithmetic',
    'Algebra1',
    'Algebra 2',
    'Geometry',
    'Trigonometry',
    'Calculus',
    'Pre Calculus',
    'Statistics and Probability',
    'Applied Mathematics',
    'Linear algebra',
    'Differential equations',
    'GRE Math',
    'Common Core Math',
    'Korean',
    'Japanese',
    'Swedish',
    'Greek',
    'Hebrew',
    'Latin',
    'Hungarian',
    'Danish',
    'Polish',
    'Finnish',
    'Portuguese',
    'Dutch',
    'Chinese',
    'Mandarin',
    'Hindi',
    'Arabic',
    'English',
    'Italian',
    'German',
    'Spanish',
    'French',
    'ESL/ESOL',
    'Russian',
    'Portuguese',
    'Romanian',
    'Vietnamese',
    'Turkish',
    'Malayalam',
    'Tamil',
    'Hungarian',
    'Financial Modeling',
    'QuickBooks Online',
    'Depreciation and Amortization',
    'Variance Analysis',
    'Capital Budgeting',
    'Auditing Principles and Practices',
    'Commercial Law',
    'Accounting',
    'Project Management',
    'Business and Economics',
    'Microeconomics',
    'Macroeconomics',
    'Managerial Accounting',
    'Tax Accounting',
    'Series 63',
    'Series 7',
    'Series 3',
    'Series 66',
    'Series 65',
    'Series 6',
    'Business ethics',
    'Business Management',
    'MBA',
    'Computer Science',
    'CCNA',
    'Data Science',
    'Modal Logic',
    'HTML',
    'C++',
    'UNIX',
    'Fortran',
    'JavaScript',
    'Linux',
    'Pascal',
    'Perl',
    'Network Computer',
    'Hardware Computer',
    'Artificial Intelligence (AI)',
    'Computer Graphics',
    'Visualization',
    'SQL',
    'jQuery',
    'Data structures and algorithms',
    'Computer architecture',
    'Programming',
    'Coding',
    'Python',
    'Angular Framework',
    'React Framework',
    'MongoDB',
    'MySQL',
    'Ruby',
    'Java',
    'PHP',
    'Swift',
    'Macintosh',
    'CSS',
    'C#',
    'ASP.NET',
    'Computer Gaming',
    'Gaming Developer',
    'MATLAB',
    'Desktop Publishing',
    'Drawing',
    'Painting',
    'Sculpture',
    'Graphic Design',
    'Digital Design',
    'Adobe Illustrator',
    'Adobe Photoshop',
    'Adobe Flash',
    'Music Production',
    'Adobe Lightroom',
    'Adobe Animate',
    'Acting',
    'Art History',
    'Dance',
    'Photography',
    'Video Production',
    'Web Design',
    'Studio art',
    'Theater and drama Film studies',
    'Music Theory',
    'Vocal Training',
    'Music History',
    'French Horn',
    'Violin',
    'Guitar',
    'Piano',
    'Harp',
    'Country Singing',
    'Opera voice',
    'Ukulele',
    'Arrangement and composition',
    'Classical piano',
    'Viola',
    'Journalism',
    'Media Literacy',
    'Political Science',
    'ACT English',
    'ACT Reading',
    'ACT Math',
    'PSAT',
    'SSAT',
    'Accuplacer',
    'STAAR',
    'ISEE',
    'NYSED Regents',
    'SAT',
    'ACT',
    'GRE',
    'GMAT',
    'TOEFL',
    'IELTS',
    'AP exam',
    'LSAT',
    'OET',
    'ASVAB',
    'MCAT',
    'USMLE',
    'NCLEX-RN',
    'AFOQT',
    'NCLEX-PN',
    'SAT Reading',
    'ABMS',
    'NBME',
    'CPA',
    'CFP',
    'CIMA',
    'ACCA',
    'NES Exams',
    'MPRE',
    'GED',
    'Phonics',
      'Phonemic Awareness',
      'Grammar',
      'Sentence Structure',
      'Vocabulary Development Proofreading',
      'Spelling',
      'Elementary Grammar',
      'Elementary Reading',
      'Elementary Vocabulary',
      'Reading',
      'English Writing',
      'Grammar',
      'Public Speaking',
      'TOEFL',
      'Literature',
      'SAT Reading',
      'Advanced Language and Composition',
      'American and World Literature',
      'International English Language Testing System (IELTS)',
      'Occupational English Test (OET)',
      'Professional Writing Skills',
      'ESL',
      'ESOL',
      'AP English Literature',
      'AP English Language',
      'AP Biology',
      'AP US History',
      'AP World History',
      'AP Calculus',
      'AP Statistics',
      'AP Physics',
      'Marine Biology',
      'Physical Science',
      'Biostatistics',
      'Elementary Science',
      'Pharmacology',
      'Archaeology',
      'Biochemistry',
      'Microbiology',
      'Medical Coding',
      'Chemistry',
      'Physics',
      'Earth and Space Sciences',
      'Biology',
      'Life Sciences',
      'Organic Chemistry',
      'ACT Science',
      'Praxis',
      'Anatomy',
      'Psychology',
      'Geology',
      'Environmental Science',
      'Astronomy',
      'Nursing',
      'Astrology',
      'Civil Engineering',
      'Computer Engineering',
      'Electrical Engineering',
      'Mechanical Engineering',
      'Industrial Engineering',
      'Chemical Engineering',
      'Reading',
      'Autism Spectrum Disorder (ASD)',
      'Intellectual Disabilities',
      'Study Skills',
      'Elementary Math',
      'ADHD',
      'Dyslexia',
      'Elementary (K-6th)',
      'Sign Language',
      'Phonics',
      'Transition Planning',
      'Microsoft Project',
      'Microsoft Excel',
      'Microsoft Office',
      'Microsoft PowerPoint',
      'Microsoft Word',
      'Microsoft Outlook',
      'Football',
      'Soccer',
      'Cricket',
      'Basketball',
      'Tennis',
      'Gymnastics',
      'Karate',
      'Kung fu',
      'Brazilian jiu-jitsu',
      'Career Development',
      'Needlework',
      'Theology',
      'Pastoral Theology',
      'Jewish History',
      'College Counseling',
      'Motor Skills Development',
      'Keyboarding',
      'Biblical Counseling',
      'Real Estate',
      'Common Core',
      'Cooking',
      'Apologetics',
      'Sociology',
      'Economics',
      'Anthropology',
      'History',
      'Health Coaching',
      'Life Coaching',
      'Behavioral Therapy',
      'Speech Therapy',
      'Occupational Therapy',
      'Nondestructive Testing']


    // take each array elements  with its index . (loop)
    // generate a newArray without that index element 
    // check if elemnt includes in newArray 
    // push to remaining subjects array.

    fullArray.forEach((key,element) => {
        console.log("key-->>>>",key)
        console.log("element-->>>>",element) 
    });

    res.status(200).send({data:fullArray});
});

export default router;